[package]
name = "termbox"
version = "0.0.5"
authors = ["Daggerbot <daggerbot@gmail.com>"]
description = "High level binding to Termbox."
repository = "https://github.com/daggerbot/termbox.rs.git"
license = "MIT"

[dependencies]
bitflags = "*"
libc = "*"
